name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install PHPCS + WP standards
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require "wp-coding-standards/wpcs"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs
      - name: PHPCS
        run: phpcs --standard=WordPress --extensions=php theme-aifm-*/ plugin-aifm-core/

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Init + Install ESLint
        run: |
          npm init -y
          npm install eslint --save-dev
          npx eslint --init || true
      - name: ESLint
        run: npx eslint "theme-aifm-*/assets/js/**/*.js" || true

  lighthouse:
    runs-on: ubuntu-latest
    if: ${{ secrets.LHCI_URL_MAIN != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ secrets.LHCI_URL_MAIN }}
          uploadArtifacts: true
